### PR TITLE
Removed unused config files

### PR DESCRIPTION
**Pull request by shenanigansd**
Remove the multiple unused config files left over from the generator that're just making a mess and causing confusion.

### CODE REVIEW

**Review by Robin5605 — CHANGES_REQUESTED** [review]
You can probably also kill `.stackblitzrc`

**Comment by shenanigansd** [comment]
> You can probably also kill `.stackblitzrc`

e1760ecf06209a29397c18180e8fe85d99eb9faa

**Review by import-pandas-as-numpy — APPROVED** [review]
:shipit:

**Review by Robin5605 — APPROVED** [review]
lgtm shipit

**Pull request merged**
